# Generated by Django 3.0.7 on 2020-11-14 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('meat', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3)),
                ('injection', models.CharField(max_length=100)),
                ('rub', models.CharField(max_length=100)),
                ('mop_sauce', models.CharField(max_length=100)),
                ('pit', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('pit_temp', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('final_temp', models.IntegerField()),
                ('personal_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('judge_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('award', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, max_length=360, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
